#!/usr/bin/expect -f
#exp_internal 1
# Author: Abbas Moghtanei
# This expect script downlaods any file from hills to my machine.
#
set timeout 20
set file [lindex $argv 0]
spawn bash -c "scp your_userid\@hills.ccsf.edu:$file ."
expect "*?assword:*"
send -- "your_password\r"
send -- "\r"
expect eof

