#!/usr/bin/expect -f
#exp_internal 1
# Author: Abbas Moghtanei
# This expect script send any file to hills.
#
set timeout 20
set file [lindex $argv 0]
set dir  [lindex $argv 1]
spawn bash -c "scp $file your_userid\@hills.ccsf.edu:$dir"
expect "*?assword:*"
send -- "your_password\r"
send -- "\r"
expect eof

